import type { Booking, Provider } from './types';

export const providers: Provider[] = [
  { id: 'p1', name: 'Ahmad H.', skills: ['ac', 'electrician'], zone: 'Achrafieh', load: 0, active: true },
  { id: 'p2', name: 'Sami K.', skills: ['ac', 'plumber'], zone: 'Metn', load: 1, active: true },
  { id: 'p3', name: 'Rabih M.', skills: ['electrician'], zone: 'Jdeideh', load: 0, active: true },
  { id: 'p4', name: 'Georges A.', skills: ['painter', 'carpenter'], zone: 'Baabda', load: 2, active: true },
  { id: 'p5', name: 'Walid T.', skills: ['plumber', 'handyman'], zone: 'Hamra', load: 0, active: true },
];

export const initialBookings: Booking[] = [
  {
    id: 'b1',
    ref: 'HS-1042',
    serviceId: 'ac',
    serviceName: 'AC',
    icon: '❄️',
    customerName: 'Rana K.',
    customerPhone: '+961 70 123 456',
    description: 'Not cooling, makes a noise',
    area: 'Achrafieh',
    landmark: 'Near Sassine, blue building, 4th floor',
    pin: '33.88712, 35.51324',
    timePref: 'ASAP',
    createdAt: '2 min ago',
    status: 'requested',
  },
  {
    id: 'b2',
    ref: 'HS-1041',
    serviceId: 'plumber',
    serviceName: 'Plumber',
    icon: '🔧',
    customerName: 'Karim D.',
    customerPhone: '+961 71 998 220',
    description: 'Kitchen sink leaking under the cabinet',
    area: 'Hamra',
    landmark: 'Bliss street, above the pharmacy',
    pin: '33.89690, 35.48010',
    timePref: 'Today · 2–5 PM',
    createdAt: '18 min ago',
    status: 'quoted',
    quoteAmount: 50,
    quoteCurrency: 'USD',
    quoteNote: 'Leak repair + parts',
  },
  {
    id: 'b3',
    ref: 'HS-1040',
    serviceId: 'electrician',
    serviceName: 'Electrician',
    icon: '⚡',
    customerName: 'Nour S.',
    customerPhone: '+961 76 445 112',
    description: 'Half the apartment has no power',
    area: 'Jdeideh',
    landmark: 'Main road, next to the bakery',
    pin: '33.89901, 35.56720',
    timePref: 'Today · 11 AM–2 PM',
    createdAt: '40 min ago',
    status: 'accepted',
    quoteAmount: 28,
    quoteCurrency: 'USD',
    quoteNote: 'Breaker + wiring check',
  },
  {
    id: 'b4',
    ref: 'HS-1039',
    serviceId: 'painter',
    serviceName: 'Painter',
    icon: '🎨',
    customerName: 'Lea B.',
    customerPhone: '+961 70 882 010',
    description: 'Repaint one bedroom, walls + ceiling',
    area: 'Baabda',
    landmark: 'Old Saida road, white gate',
    pin: '33.83390, 35.54410',
    timePref: 'Sat',
    createdAt: '1 hr ago',
    status: 'assigned',
    quoteAmount: 120,
    quoteCurrency: 'USD',
    providerId: 'p4',
  },
];

// Completed jobs for the History tab.
export const historyBookings: Booking[] = [
  {
    id: 'h1', ref: 'HS-1038', serviceId: 'ac', serviceName: 'AC service', icon: '❄️',
    customerName: 'Maya R.', customerPhone: '+961 70 111 222', description: 'Service + gas',
    area: 'Achrafieh', landmark: '', pin: '', timePref: '', createdAt: 'Yesterday',
    status: 'paid', quoteAmount: 35, quoteCurrency: 'USD', providerId: 'p1', rating: 5,
  },
  {
    id: 'h2', ref: 'HS-1035', serviceId: 'plumber', serviceName: 'Plumber', icon: '🔧',
    customerName: 'Tarek N.', customerPhone: '+961 71 333 444', description: 'Blocked drain',
    area: 'Hamra', landmark: '', pin: '', timePref: '', createdAt: '2 days ago',
    status: 'paid', quoteAmount: 50, quoteCurrency: 'USD', providerId: 'p5', rating: 4,
  },
  {
    id: 'h3', ref: 'HS-1031', serviceId: 'electrician', serviceName: 'Electrician', icon: '⚡',
    customerName: 'Hadi F.', customerPhone: '+961 76 555 666', description: 'Outlet install',
    area: 'Jdeideh', landmark: '', pin: '', timePref: '', createdAt: '3 days ago',
    status: 'paid', quoteAmount: 28, quoteCurrency: 'USD', providerId: 'p3', rating: 5,
  },
  {
    id: 'h4', ref: 'HS-1027', serviceId: 'painter', serviceName: 'Painter', icon: '🎨',
    customerName: 'Carla M.', customerPhone: '+961 70 777 888', description: 'Living room',
    area: 'Baabda', landmark: '', pin: '', timePref: '', createdAt: '4 days ago',
    status: 'paid', quoteAmount: 120, quoteCurrency: 'USD', providerId: 'p4', rating: 3,
  },
  {
    id: 'h5', ref: 'HS-1024', serviceId: 'ac', serviceName: 'AC repair', icon: '❄️',
    customerName: 'Omar Z.', customerPhone: '+961 71 999 000', description: 'Not turning on',
    area: 'Metn', landmark: '', pin: '', timePref: '', createdAt: '5 days ago',
    status: 'paid', quoteAmount: 45, quoteCurrency: 'USD', providerId: 'p2',
  },
];
